# The Numpy Arrays



In [1]:
import numpy as np

a = np.array([0, 1, 2, 3])
print(a)


[0 1 2 3]


In [4]:
#type()- method returns class type of the argument(object) passed as parameter
type(a) 

numpy.ndarray

In [5]:
a = [0,1,2,3,4]
a
type(a)

list

In [9]:
ar1 = np.array(a)
ar1


array([0, 1, 2, 3, 4])

In [8]:
type(ar1)

numpy.ndarray

In [ ]:
print(np.arange(10))

# 1. Basic Operations

In [10]:
_list = [0,1,2,3,4]
_list

_arr1d = np.array(_list)
_arr1d

array([0, 1, 2, 3, 4])

In [11]:
print(_arr1d + 2)


[2 3 4 5 6]


In [12]:
print(_arr1d * 4)

[ 0  4  8 12 16]


**Why it is useful:** Memory-efficient container that provides fast numerical operations.

# 2. Creating arrays

1.1.  Standard Construction of arrays

In [13]:
#1-D

a = np.array([0, 1, 2, 3])

a

array([0, 1, 2, 3])

In [14]:
#print dimensions

a.ndim

1

In [15]:
#shape

a.shape

(4,)

In [16]:
len(a)

4

In [17]:
# 2-D, 3-D....

b = np.array([[0, 1, 2], [3, 4, 5]])

b

array([[0, 1, 2],
       [3, 4, 5]])

In [18]:
b.ndim

2

In [19]:
b.shape

(2, 3)

In [20]:
len(b) #returns the size of the first dimention

2

In [21]:
c = np.array([[[0, 1], [2, 3]], [[4, 5], [6, 7]]])

c

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [22]:
c.ndim

3

In [23]:
#shape- The shape of an array is the number of elements in each dimension.
c.shape

(2, 2, 2)

** 1.2  Functions for creating arrays**

In [26]:
#using arrange function

# arange is an array-valued version of the built-in Python range function

a = np.arange(10) # 0.... n-1
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
b = np.arange(1, 10, 2) #start, end (exclusive), step

b

array([1, 3, 5, 7, 9])

In [29]:
#using linspace

a = np.linspace(0, 1, 6) #start, end, number of points

a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [30]:
#common arrays

a = np.ones((3, 3))

a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [31]:
b = np.zeros((3, 2))

b

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [32]:
c = np.eye(3)  #Return a 2-D array with ones on the diagonal and zeros elsewhere.

c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
d = np.eye(3, 2) #3 is number of rows, 2 is number of columns, index of diagonal start with 0

d

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [34]:
#create array using diag function

a = np.diag([1, 2, 3, 4]) #construct a diagonal array.

a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [35]:
np.diag(a)   #Extract diagonal

array([1, 2, 3, 4])

In [38]:
#https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html
#create array using random
#Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).


a = np.random.rand(40) 

a

array([0.09177528, 0.64948031, 0.97594052, 0.22752545, 0.12009405,
       0.91018351, 0.65265543, 0.14531728, 0.98798984, 0.23403547,
       0.15540905, 0.00865445, 0.76564474, 0.65269937, 0.31492362,
       0.98613306, 0.72147394, 0.6433021 , 0.99302234, 0.63278873,
       0.06369133, 0.55266323, 0.9186722 , 0.39939322, 0.38502945,
       0.28399848, 0.50894441, 0.21143916, 0.86733709, 0.06660263,
       0.59885525, 0.0714055 , 0.41606367, 0.00293426, 0.63147556,
       0.66053912, 0.78224405, 0.62184128, 0.23597232, 0.72585726])

In [39]:
a = np.random.randn(4)#Return a sample (or samples) from the “standard normal” distribution.  ***Gausian***

a

array([ 1.21533957, -1.31644424, -0.36361373, -0.86951478])

**Note:**
    
For random samples from N(\mu, \sigma^2), use:

sigma * np.random.randn(...) + mu



# 2. Basic DataTypes

In some instances, array elements are displayed with a **trailing dot (e.g. 2. vs 2)**. This is due to a difference in the **data-type** used:

In [ ]:
a = np.arange(10)

a.dtype

In [ ]:
#You can explicitly specify which data-type you want:

a = np.arange(10, dtype='float64')
a

In [ ]:
#The default data type is float for zeros and ones function

a = np.zeros((3, 3))

print(a)

a.dtype

**More datatypes**

In [40]:
d = np.array([1+2j, 2+4j])   #Complex datatype

print(d.dtype)

complex128


In [41]:
b = np.array([True, False, True, False])  #Boolean datatype

print(b.dtype)

print(type(b))

bool
<class 'numpy.ndarray'>


In [42]:
s = np.array(['Amar', 'Akbar', 'Anthony'])

s.dtype

dtype('<U7')

**Each built-in data type has a character code that uniquely identifies it.**

'b' − boolean

'i' − (signed) integer

'u' − unsigned integer

'f' − floating-point

'c' − complex-floating point

'm' − timedelta

'M' − datetime

'O' − (Python) objects

'S', 'a' − (byte-)string

'U' − Unicode

'V' − raw data (void)

**For more details**

**https://docs.scipy.org/doc/numpy-1.10.1/user/basics.types.html**

# 3. Indexing and Slicing

**3.1 Indexing**

The items of an array can be accessed and assigned to the same way as other **Python sequences (e.g. lists)**:

In [46]:
a = np.arange(10)

print(5)  #indices begin at 0, like other Python sequences (and C/C++)

5


In [47]:
# For multidimensional arrays, indexes are tuples of integers:

a = np.diag([1, 2, 3])

print(a[2, 2])

3


In [ ]:
a[2, 1] = 5 #assigning value

a

**3.2 Slicing**

In [48]:
a = np.arange(10)

a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
a[1:8:2] # [startindex: endindex(exclusive) : step]

array([1, 3, 5, 7])

In [50]:
#we can also combine assignment and slicing:

a = np.arange(10)
a[5:] = 10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [51]:
b = np.arange(5)
a[5:] = b[::-1]  #assigning

a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])